#!/bin/bash
clear

echo '%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%'
echo '%       %%     %%%%%%%%        %%%%         %%%        *%%%%  %%%%%%  %%%         %%%          %%%        %%%%%%%        %%%%%  %%%%%%%'
echo '%         %%   %%%%%%%  %%%%%%%%%%  %%%%%%%%%%%  %%%%%  %%%%  %%%%%%  %%%  %%%%%%  %%%%%%  %%%%%%  %%%%%%   %%%   %%%%%%  %%%%  %%%%%%%'
echo '%%%         %% %%%%%%%    %%%%%%%#  %%%%%%%%%%%  %%%%%  %%%%  %%%%%%  %%%         %%%%%%%  %%%%%%  %%%%%%%  %%%  %%%%%%%%  %%%  %%%%%%%'
echo '% %%%        %%%%%%%%%%%%%    %%%#  %%%%%%%%%%%       %%%%%%  %%%%%%  %%%  %%%%%%  %%%%%%  %%%%%%  %%%%%%%  %%%  %%%%%%%%  %%%  %%%%%%%'
echo '%   %%%        %%%%%%%%%%%%%%  %%%  %%%%%%%%%%%  %%%%  %%%%%  %%%%%%  %%%  %%%%%%  %%%%%%  %%%%%%  %%%%%%%  %%%%  %%%%%%  %%%%  %%%%%%%'
echo '%     %%       %%%%%%%        %%%%%        %%%%  %%%%%  %%%%%       *%%%%         %%%%%%%  %%%%%%%        %%%%%%%        %%%%%        %'
echo '%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%'

if [ -z "$(which php73)" ]
then
  php=$(which php)
else
  php=$(which php73)
fi

$php --version

if [ -z "$(which composer)" ]
then
  echo "Could not find composer"
else
  $php -n "$(which composer)" install
fi

rm -rf ./storage/app/private
npm run watch &

$php artisan optimize -v
$php artisan cache:clear -v
$php artisan route:clear -v
$php artisan view:clear -v
$php artisan migrate:fresh --seed -v
queue='artisan queue:listen --queue=analyze,run,notify,build,delete --timeout=0 -v'
$php $queue &

$php artisan serve --port=1234 -v

ps ax | grep "$queue" | awk -F ' ' '{print $1}' | xargs kill -2 >/dev/null 2>&1
ps ax | grep "npm run watch" | awk -F ' ' '{print $1}' | xargs kill -2 >/dev/null 2>&1
